### ISSUE TITLE
Incompatibility with ember-cli-stylus

### ISSUE THREAD

**Issue by WooDzu** [ExpressCheckout/ember-cli-ramdisk#9]
I'm using ember stylus addon extensively with globe imports eg:

* @import "../../app/modules/components/*/style"

version: 0.1.11
node: 0.10.26
npm: 2.1.8

```
===== 2 JSHint Errors

/mnt/EmberCliRamdisk/flow/tree_merger-tmp_dest_dir-xTkaYnsC.tmp//app/styles/app.styl:12:9
    8| @import "forms/default"
    9| @import "forms/icons"
   10| 
   11| // Ember Components
   12| @import "../../app/modules/components/*/style"
---------------^
   13| 
   14| // Ember Modules (pods)
   15| @import "../../app/modules/*/styles/index"

failed to locate @import file ../../app/modules/components/*/style.styl
```

Then it fails with:

```

Error: /mnt/EmberCliRamdisk/flow/tree_merger-tmp_dest_dir-xTkaYnsC.tmp//app/styles/app.styl:12:9
    8| @import "forms/default"
    9| @import "forms/icons"
   10| 
   11| // Ember Components
   12| @import "../../app/modules/components/*/style"
---------------^
   13| 
   14| // Ember Modules (pods)
   15| @import "../../app/modules/*/styles/index"

failed to locate @import file ../../app/modules/components/*/style.styl

    at Evaluator.visitImport (/CUT/node_modules/ember-cli-stylus/node_modules/stylus/lib/visitor/evaluator.js:898:21)
    at Evaluator.Visitor.visit (/CUT/node_modules/ember-cli-stylus/node_modules/stylus/lib/visitor/index.js:28:40)
    at Evaluator.visit (/CUT/node_modules/ember-cli-stylus/node_modules/stylus/lib/visitor/evaluator.js:153:18)
    at Evaluator.visitRoot (/CUT/node_modules/ember-cli-stylus/node_modules/stylus/lib/visitor/evaluator.js:689:27)
    at Evaluator.Visitor.visit (/CUT/node_modules/ember-cli-stylus/node_modules/stylus/lib/visitor/index.js:28:40)
    at Evaluator.visit (/CUT/node_modules/ember-cli-stylus/node_modules/stylus/lib/visitor/evaluator.js:153:18)
    at Evaluator.evaluate (/CUT/node_modules/ember-cli-stylus/node_modules/stylus/lib/visitor/evaluator.js:229:15)
    at Renderer.render (/CUT/node_modules/ember-cli-stylus/node_modules/stylus/lib/renderer.js:86:26)
    at Function.exports.render (/CUT/node_modules/ember-cli-stylus/node_modules/stylus/lib/stylus.js:81:37)
    at /CUT/node_modules/ember-cli-stylus/node_modules/broccoli-stylus-single/index.js:41:16
```

**Comment by jbryson3** [comment]
It seems to choke for me on the relative pathing as well
